apiVersion: v1
kind: Service
metadata:
  name: playground-gitlab-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: playground-gitlab
  ports:
  - protocol: TCP
    port: 8889
    targetPort: 8888
