apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-gitlab
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-gitlab
  template:
    metadata:
      labels:
        app: playground-gitlab
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
