Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/bookworm64"

  config.vm.define "pbeheytS" do |control|
    control.vm.hostname = "pbeheytS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.memory = "512"
      v.cpus = 1
    end
  end

  config.vm.define "pbeheytSW" do |control|
    control.vm.hostname = "pbeheytSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.memory = "512"
      v.cpus = 1
    end
  end

end
